export type HueApiLight = typeof hueApiLightSample;
export const hueApiLightSample = {
  '1': {
    state: {
      on: false,
      bri: 154,
      alert: 'select',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T12:22:02',
    },
    type: 'Dimmable light',
    name: 'Hulfeværelse (bulb)',
    modelid: 'LWA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue white lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 5000,
        maxlumen: 800,
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'classicbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'powerfail',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LWA001-1-A19DLv5',
  },
  '4': {
    state: {
      on: false,
      bri: 25,
      hue: 7148,
      sat: 225,
      effect: 'none',
      xy: [0.527, 0.413],
      ct: 497,
      alert: 'select',
      colormode: 'xy',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Extended color light',
    name: 'Trappe (light strip)',
    modelid: 'LCL001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue lightstrip plus',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 40,
        maxlumen: 1600,
        colorgamuttype: 'C',
        colorgamut: [
          [0.6915, 0.3083],
          [0.17, 0.7],
          [0.1532, 0.0475],
        ],
        ct: {
          min: 153,
          max: 500,
        },
      },
      streaming: {
        renderer: true,
        proxy: true,
      },
    },
    config: {
      archetype: 'huelightstrip',
      function: 'mixed',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LCL001-1-LedStripsv4',
  },
  '5': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, køkkenbord #4',
    modelid: 'LTA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 800,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LTA001-2-A19CTv3',
  },
  '6': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, køkkenbord #2',
    modelid: 'LTA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 800,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LTA001-2-A19CTv3',
  },
  '7': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, køkkenbord #1',
    modelid: 'LTA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 800,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LTA001-2-A19CTv3',
  },
  '8': {
    state: {
      on: true,
      bri: 80,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, køkkenbord #3',
    modelid: 'LTA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 800,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LTA001-2-A19CTv3',
  },
  '9': {
    state: {
      on: false,
      bri: 254,
      ct: 363,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'soveværelse spot #2',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'powerfail',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '10': {
    state: {
      on: false,
      bri: 254,
      ct: 363,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'soveværelse spot #4',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'powerfail',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '11': {
    state: {
      on: false,
      bri: 254,
      ct: 363,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'soveværelse spot #3',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'powerfail',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '12': {
    state: {
      on: false,
      bri: 254,
      ct: 363,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'soveværelse spot #1',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'powerfail',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '14': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T22:42:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, spisebord',
    modelid: 'LTA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 800,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LTA001-2-A19CTv3',
  },
  '15': {
    state: {
      on: false,
      bri: 190,
      alert: 'select',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T02:12:02',
    },
    type: 'Dimmable light',
    name: 'Vaske, vaskemaskine',
    modelid: 'LWB010',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue white lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 2000,
        maxlumen: 806,
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'classicbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.50.2_r30933',
    swconfigid: '...',
    productid: 'Philips-LWB010-1-A19DLv4',
  },
  '16': {
    state: {
      on: false,
      bri: 190,
      alert: 'select',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T02:12:02',
    },
    type: 'Dimmable light',
    name: 'Vaske, gang',
    modelid: 'LWA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue white lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 5000,
        maxlumen: 800,
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LWA001-1-A19DLv5',
  },
  '17': {
    state: {
      on: false,
      bri: 254,
      ct: 363,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T12:42:02',
    },
    type: 'Color temperature light',
    name: 'soveværelse seng',
    modelid: 'LTW010',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 1000,
        maxlumen: 806,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'powerfail',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.50.2_r30933',
    swconfigid: '...',
    productid: 'Philips-LTW010-1-A19CTv2',
  },
  '18': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T02:42:02',
    },
    type: 'Color temperature light',
    name: 'Badeværelse, main',
    modelid: 'LTA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 800,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LTA001-2-A19CTv3',
  },
  '19': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, spot #1',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '20': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, spot #2',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '22': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Entré #3',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '23': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Entré #2',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '24': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Entré #5',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '25': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Entré #4',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '26': {
    state: {
      on: true,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Entré #1',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '27': {
    state: {
      on: true,
      bri: 80,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Køkken, spot #3',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '29': {
    state: {
      on: false,
      bri: 152,
      hue: 7148,
      sat: 225,
      effect: 'none',
      xy: [0.527, 0.413],
      ct: 497,
      alert: 'select',
      colormode: 'xy',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T12:42:02',
    },
    type: 'Extended color light',
    name: 'Stuen, main',
    modelid: 'LCA001',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue color lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 800,
        colorgamuttype: 'C',
        colorgamut: [
          [0.6915, 0.3083],
          [0.17, 0.7],
          [0.1532, 0.0475],
        ],
        ct: {
          min: 153,
          max: 500,
        },
      },
      streaming: {
        renderer: true,
        proxy: true,
      },
    },
    config: {
      archetype: 'sultanbulb',
      function: 'mixed',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.10',
    swconfigid: '...',
    productid: 'Philips-LCA001-5-A19ECLv6',
  },
  '30': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Badeværelse spot #1',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '31': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Badeværelse spot #2',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '32': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Badeværelse spot #3',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '33': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Gang, 1. sal #3',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '34': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Gang, 1. sal #2',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '35': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Gang, 1. sal #1',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '36': {
    state: {
      on: false,
      bri: 152,
      ct: 454,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Gang, 1. sal #4',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '37': {
    state: {
      on: false,
      bri: 254,
      ct: 363,
      alert: 'select',
      colormode: 'ct',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-12T02:02:02',
    },
    type: 'Color temperature light',
    name: 'Stuen, under trappe #1',
    modelid: 'LTG002',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue ambiance spot',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 200,
        maxlumen: 350,
        ct: {
          min: 153,
          max: 454,
        },
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'spotbulb',
      function: 'functional',
      direction: 'downwards',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.76.8',
    swconfigid: '...',
    productid: 'Philips-LTG002-3-GU10CTv2',
  },
  '38': {
    state: {
      on: false,
      bri: 152,
      alert: 'select',
      mode: 'homeautomation',
      reachable: true,
    },
    swupdate: {
      state: 'noupdates',
      lastinstall: '2020-02-02T12:32:02',
    },
    type: 'Dimmable light',
    name: 'Toilet',
    modelid: 'LWB010',
    manufacturername: 'Signify Netherlands B.V.',
    productname: 'Hue white lamp',
    capabilities: {
      certified: true,
      control: {
        mindimlevel: 2000,
        maxlumen: 806,
      },
      streaming: {
        renderer: false,
        proxy: false,
      },
    },
    config: {
      archetype: 'classicbulb',
      function: 'functional',
      direction: 'omnidirectional',
      startup: {
        mode: 'safety',
        configured: true,
      },
    },
    uniqueid: '...',
    swversion: '1.50.2_r30933',
    swconfigid: '...',
    productid: 'Philips-LWB010-1-A19DLv4',
  },
};
